### ISSUE TITLE
distinct repos, c and c++ version merging. 

### ISSUE THREAD

**Issue by juztas** [cmscaltech/apmon#3]
Good suggestions from Adrian (sorry, don't know your git username and can't tag). After point 1, we need to merge version which you have and the one which is here already. 
at this moment i would have just 2 small comments :
1. given that each section have distinct building procedures
wouldn't make more sense to have distinct repositories for each language?

2. i wonder if wouldn't be more efficient to merge the c and c++ versions? (see use cases and differences and accommodate the common usage of required includes?) (maybe something like : make all c++ and create includes for c that make use of c++ code?)

**Comment by adriansev** [comment]
present :) so, my version have the perl modules in it (but those modules are not involved in build process so they can be removed.)
in fact i will do for myself an repository for those modules in order to prepare an spec file for their installation (and maybe it will be also useful to you)

**Comment by adriansev** [comment]
and about c/c++ merging : i think that the first step would be to identify the c applications that use the c libraries and includes.

**Comment by juztas** [comment]
Repos separated and all new issues were created. Closing and removing this repo.

**Comment by juztas** [comment]
All code will live here: https://github.com/MonALISA-CIT
